### 3.1 One-Hot 编码

### 每一列特征需要构建的状态寄存器的位数等于该列特征独立取值的个数
#### 使用N位状态寄存器来对N个状态进行编码，每个状态都由他独立的寄存器位，并且在任意时候，其中只有一位有效。

In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing

In [3]:
enc = preprocessing.OneHotEncoder()
enc.fit_transform([[0, 0, 3], [1, 1, 0], [0, 2, 1], [1, 0, 2]]).toarray()  
#第一列有两个状态：0、1，需要2位状态寄存器来进行编码，[1,0]表示0,[0,1]表示1
#第二列有三个状态：0、1、2，需要3位状态寄存器来进行编码，[1,0,0]表示0，[0,1,0]表示1，[0,0,1]表示2
#第三列有四个状态：0、1、2、3，需要4位状态寄存器来进行编码，[1,0,0,0]表示0，[0,1,0,0]表示1，[0,0,1,0]表示2，[0,0,0,1]表示3

array([[ 1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.],
       [ 0.,  1.,  1.,  0.,  0.,  0.,  0.,  1.,  0.]])

In [4]:
enc.transform([[0, 1, 3]]).toarray()

array([[ 1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.]])

#### 如果训练集中有丢失的分类特征值，必须显式地设置n_values

In [4]:
# n_values=[2, 3, 4]表示第1/2/3列分别有2/3/4个独立取值
enc = preprocessing.OneHotEncoder(n_values=[2, 3, 4]) 
enc.fit([[1, 2, 3], [0, 2, 0]])  

OneHotEncoder(categorical_features='all', dtype=<class 'numpy.float64'>,
       handle_unknown='error', n_values=[2, 3, 4], sparse=True)

In [5]:
enc.transform([[1, 0, 0]]).toarray()

array([[0., 1., 1., 0., 0., 1., 0., 0., 0.]])

### 3.2 pandas.get_dummies构造哑变量

##### pandas.get_dummies(data, prefix=None, prefixsep='', dummy_na=False, columns=None, sparse=False, drop_first=False)

In [6]:
dict_ = {'Nation': ['CN', 'US', 'UK'], 'Explorer': ['Firefox','Chrome','Safari'], 'Quantity': [1, 2, 3]}
df = pd.DataFrame(dict_)
df

Explorer Nation  Quantity
0  Firefox     CN         1
1   Chrome     US         2
2   Safari     UK         3

In [7]:
df_dummies = pd.get_dummies(df, prefix=['Explorer', 'Nation'], prefix_sep='_')    
df_dummies

Quantity  Explorer_Chrome  Explorer_Firefox  Explorer_Safari  Nation_CN  \
0         1                0                 1                0          1   
1         2                1                 0                0          0   
2         3                0                 0                1          0   

   Nation_UK  Nation_US  
0          0          0  
1          0          1  
2          1          0